students = ["Axel",
            "Algot",
            "Axel",
            "Daniel",
            "Anton",
            "Dennis",
            "Filip",
            "Tage",
            "Anton",
            "Lukas",
            "Max",
            "Victor",
            "Hugo"]
